import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Header from "@/app/components/Header"; // 👈 Import your Header component
import Header from "./component/navbar";
import Footer from "./component/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MT shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  data-theme="light">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header /> 
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
